# backend/kernel/models/query_plan.py

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class StepType(StrEnum):
    FETCH_VECTOR = "fetch_vector"  # Get features from DB/API
    FETCH_RASTER = "fetch_raster"  # Get raster bands from local/GEE
    SPATIAL_JOIN = "spatial_join"  # Intersect, Within, Distance analysis
    ZONAL_STATS = "zonal_stats"  # Compute raster statistics over zones
    TEMPORAL_FILTER = "temporal_filter"  # Filter by dates/ranges
    UNION = "union"  # Combine multiple datasets
    INTERSECTION = "intersection"  # Keep overlapping parts only
    AGGREGATE = "aggregate"  # Group by, count, average
    EXTERNAL_API_CALL = "api_call"  # Fetch routing, geocoding
    RENDER_GRID = "render_grid"  # Generate contour/heatmap


class PlanStep(BaseModel):
    """A single atomic operation in a multi-source geospatial execution plan."""

    id: str = Field(default_factory=lambda: f"step_{uuid4().hex}")
    type: StepType
    name: str

    # Resources needed
    datasource_ids: list[str] = Field(default_factory=list)

    # Steps that must finish before this step can run (DAG structure)
    dependencies: list[str] = Field(default_factory=list)

    # Step-specific operation parameters (e.g., buffer radius, band name, join key)
    parameters: dict[str, Any] = Field(default_factory=dict)

    # Estimated cost or weight (for optimization)
    cost_estimate: float | None = None

    metadata: dict[str, Any] = Field(default_factory=dict)


class QueryPlan(BaseModel):
    """
    A Directed Acyclic Graph (DAG) of PlanSteps.
    Generated by the planner from QueryIR and executed by the Engine.
    """

    id: str = Field(default_factory=lambda: f"plan_{uuid4().hex}")
    query_ir_id: str

    # Steps ordered topologically or as a DAG
    steps: list[PlanStep] = Field(default_factory=list)

    # Estimated execution time
    estimated_duration_ms: float | None = None

    # Optimization flags
    parallel_execution_allowed: bool = True
    cache_policy: str = "default"  # "skip", "force_refresh", "default"

    metadata: dict[str, Any] = Field(default_factory=dict)

    def get_step(self, step_id: str) -> PlanStep | None:
        for step in self.steps:
            if step.id == step_id:
                return step
        return None

    @property
    def leaf_steps(self) -> list[PlanStep]:
        """Steps that have no other steps depending on them (final outputs)."""
        dependent_ids = {dep for step in self.steps for dep in step.dependencies}
        return [step for step in self.steps if step.id not in dependent_ids]
